--insert into todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
--values(10001,'Saurav', 'Get AWS Certified', CURRENT_DATE(), false);
--
--insert into todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
--values(10002,'Saurav', 'Get Azure Certified', CURRENT_DATE(), false);
--
--insert into todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
--values(10003,'Saurav', 'Get GCP Certified', CURRENT_DATE(), false);
--
--insert into todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
--values(10004,'Saurav', 'Learn DevOps', CURRENT_DATE(), false);